name: Dotfiles CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-dotfiles:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Install chezmoi
      run: |
        curl -fsLS get.chezmoi.io | bash -s -- -b ~/.local/bin
        echo "$HOME/.local/bin" >> "$GITHUB_PATH"

    - name: Apply dotfiles with chezmoi
      run: chezmoi init --apply .

    # ← ★ nightly AppImage 方式
    - name: Install Neovim nightly (AppImage)
      run: |
        curl -L https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage -o nvim.appimage
        chmod u+x nvim.appimage
        ./nvim.appimage --appimage-extract
        echo "$PWD/squashfs-root/usr/bin" >> "$GITHUB_PATH"

    - name: Install deps (ripgrep, fd)
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ripgrep fd-find

    - name: Lazy sync
      run: nvim --headless "+Lazy! sync" +qa

    - name: Run :checkhealth
      run: |
        nvim --headless "+checkhealth" "+qa" >checkhealth.log || true
        if grep -q "ERROR" checkhealth.log; then
          echo "::error::Neovim health check failed"
          cat checkhealth.log
          exit 1
        fi
        cat checkhealth.log

    - name: Final smoke test
      run: nvim --headless -c "quit"
