name: Dotfiles CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Install chezmoi
      run: |
        curl -fsLS get.chezmoi.io | bash -s -- -b ~/.local/bin
        echo "$HOME/.local/bin" >> "$GITHUB_PATH"

    - name: Apply dotfiles
      run: chezmoi init --apply .

    # ---- Neovim nightly 安定取得 ----
    - name: Install Neovim nightly (PPA)
      run: |
        sudo apt-get update -y
        sudo add-apt-repository -y ppa:neovim-ppa/unstable
        sudo apt-get update -y
        sudo apt-get install -y neovim ripgrep fd-find
        nvim --version

    - name: Lazy sync
      run: nvim --headless "+Lazy! sync" +qa

    - name: CheckHealth
      run: |
        nvim --headless "+checkhealth" +qa > checkhealth.log || true
        if grep -q "ERROR" checkhealth.log; then
          echo "::error::health check failed"
          cat checkhealth.log
          exit 1
        fi
        cat checkhealth.log
