name: Dotfiles CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: chezmoi apply
      run: |
        curl -fsLS get.chezmoi.io | bash -s -- -b ~/.local/bin
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        chezmoi init --apply .

    - name: Neovim nightly + deps
      run: |
        sudo add-apt-repository -y ppa:neovim-ppa/unstable
        sudo apt-get update -y
        sudo apt-get install -y neovim ripgrep fd-find fish peco

    - name: Lazy sync
      run: nvim --headless "+Lazy! sync" +qa

    - name: Health
      run: |
        nvim --headless "+checkhealth" "+qa" >log || true
        grep -q ERROR log && { cat log; exit 1; } || cat log
