name: Dotfiles CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      # Install mise first
      - name: Install mise
        run: |
          curl -fsSL https://mise.jdx.dev/install.sh | bash
          echo "$HOME/.local/share/mise/bin" >> "$GITHUB_PATH"

      - name: Apply dotfiles
        run: |
          curl -fsLS get.chezmoi.io | bash -s -- -b ~/.local/bin
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          chezmoi init --apply .

      - name: Install Neovim nightly
        run: |
          sudo add-apt-repository -y ppa:neovim-ppa/unstable
          sudo apt-get update -y
          sudo apt-get install -y neovim

      - name: Lazy sync
        run: nvim --headless "+Lazy! sync" +qa

      - name: Run :checkhealth
        run: |
          nvim --headless "+checkhealth" "+qa" > health.log || true
          grep -q ERROR health.log && { cat health.log; exit 1; } || cat health.log
